### ISSUE TITLE
魅蓝在微信中识别不了

### ISSUE THREAD

**Issue by chen4342024** [fex-team/ua-device#12]
魅蓝在微信中识别不了，识别成小米了

**Comment by kevindu1993** [comment]
你好，遇到过很多这样的情况呢，大部分是因为微信对于很多机型的UA信息进行了改写，但是我们目前还没有针对来自微信的数据进行一个特殊处理，导致获取到的UA信息和原始机型的信息不一致.
你可以参考这里：https://github.com/fex-team/ua-device/issues/3
