### ISSUE TITLE
Google Browser 是什么意思？

### ISSUE THREAD

**Issue by snadn** [fex-team/ua-device#13]
检测结果里面，浏览器有一项是 `Google Browser`， 版本是 4.0。

想问一下这个 Google Browser 是怎么划分的，表示的浏览器是什么？因为这个结果和 https://github.com/hotoo/detector 的检测结果相差很大。之前用 detector 的结果是分散的很多其他各个版本的浏览器，现在都变成了 Google Browser 4.0

**Comment by kevindu1993** [comment]
你好，在浏览器端做的特殊适配并不是特别全， Google Browser 是 安卓机的 Android Google Browser 的一个识别，依据主要在于安卓机以及safari关键字
