### ISSUE TITLE
无法识别猎豹浏览器

### ISSUE THREAD

**Issue by CosimoZi** [fex-team/ua-device#14]
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.154 Safari/537.36 LBBROWSER
识别为
{u'browser': {u'channel': u'Nightly',
              u'hidden': False,
              u'name': u'Chrome',
              u'stock': False,
              u'version': {u'alias': None, u'original': u'42.0.2311.154'}},
 u'camouflage': False,
 u'device': {u'identified': False, u'type': u'desktop'},
 u'engine': {u'name': u'Webkit',
             u'version': {u'alias': None, u'original': u'537.36'}},
 u'features': [],
 u'options': {u'detectCamouflage': True, u'useFeatures': False},
 u'os': {u'name': u'Windows',
         u'version': {u'alias': u'8', u'original': u'6.2'}}}

**Comment by kevindu1993** [comment]
感谢反馈问题，目前已经更新了库，谢谢支持
