### ISSUE TITLE
ios上的qq浏览器把设备类型识别成desktop，os识别成MAC OS X

### ISSUE THREAD

**Issue by chaiyanlin** [fex-team/ua-device#15]
ios上的qq浏览器把设备类型识别成desktop，os识别成MAC OS X

**Comment by Arnoldnuo** [comment]
已经不维护了吗？😢

**Comment by kevindu1993** [comment]
这个问题已经修复

**Comment by Arnoldnuo** [comment]
能否更新到npm上去？@kevindu1993

**Comment by kevindu1993** [comment]
正在修其它的问题，大概5点的时候会提npm

**Comment by kevindu1993** [comment]
现在能遇到的主流问题主要是2类：
1是 微信 qq浏览器会默认修改UA信息，比如ihone 的标配 就是 iphone; qq浏览器给出的iphone 6s是自己通过读手机其它配置加的。
2是 某些非 常见的内容无法被识别

**Comment by kevindu1993** [comment]
@Arnoldnuo 已经发npm 了
