### ISSUE TITLE
baiduboxapp 继续问

### ISSUE THREAD

**Issue by peggypan** [fex-team/ua-device#18]
ua解析出来很多的baiduboxapp，看代码中写的是‘百度框’，请问百度框是什么？是百度搜索框吗？如果是的话，为什么单独列出来呢？还望解答。

**Comment by kevindu1993** [comment]
你好，是通过手机百度进入的一个页面

**Comment by peggypan** [comment]
手机百度是百度浏览器吗？那不是还有一个baidubrowser吗？还是不明白是什么？

**Comment by peggypan** [comment]
哦，是手机百度客户端？
