### ISSUE TITLE
iOS 手机 QQ 的 ua 貌似识别失败

### ISSUE THREAD

**Issue by l5oo00** [fex-team/ua-device#24]
类似这样的 ua：

Mozilla/5.0 (iPhone 6sp; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 MQQBrowser/7.3 Mobile/14E304 Safari/8536.25 MttCustomUA/2 QBWebViewType/1

Mozilla/5.0 (iPhone 6sp; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 MQQBrowser/7.4 Mobile/13G36 Safari/8536.25 MttCustomUA/2 QBWebViewType/1 WKType/1

被识别成 Mac OS 了， 但感觉应该是 iPhone。

**Comment by kevindu1993** [comment]
嗯，我知道你说的问题了，会尽快跟进

是 微信 qq浏览器会默认修改UA信息，比如ihone 的标配 就是 iphone; qq浏览器给出的iphone 6s是自己通过读手机其它配置加的。

**Comment by l5oo00** [comment]
@kevindu1993   辛苦辛苦

**Comment by kevindu1993** [comment]
感谢反馈问题，目前已经更新了库，谢谢支持
