### ISSUE TITLE
iOS版Opera浏览器无法识别

### ISSUE THREAD

**Issue by lishuzhi1121** [fex-team/ua-device#25]
iOS版Opera的UA如下：
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) OPiOS/11.0.1.107866 Version/7.0 Mobile/14E304 Safari/9537.53
应该是可以根据OPiOS识别的，但是该库识别不了。

**Comment by kevindu1993** [comment]
感谢反馈问题，目前已经更新了库，谢谢支持
