### ISSUE TITLE
手机QQ的识别的问题

### ISSUE THREAD

**Issue by iceout** [fex-team/ua-device#30]
看到这样一个UA：

Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89 QQ/7.1.1.440 V1_IPH_SQ_7.1.1_1_APP_A Pixel/750 Core/UIWebView NetType/WIFI QBWebViewType/1

识别成Safari了

**Comment by kevindu1993** [comment]
您好，问题已收录，7月16号前统一处理

**Comment by javaside** [comment]
iPhone上的 chrome 也认成Safari了

**Comment by iceout** [comment]
@kevindu1993 辛苦，
另外，『Mozilla/5.0 (Linux; U; Android 6.0.1; zh-cn; MI 4LTE Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko)Version/4.0 Chrome/37.0.0.0 MQQBrowser/7.0 Mobile Safari/537.36』这个应该是手机QQ浏览器吧，识别为了手机QQ

**Comment by kevindu1993** [comment]
@iceout 你好，这2个是一个意思

**Comment by kevindu1993** [comment]
@iceout 请提供一个明显一些的UA
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89 QQ/7.1.1.440 V1_IPH_SQ_7.1.1_1_APP_A Pixel/750 Core/UIWebView NetType/WIFI QBWebViewType/1
这个确实看不出来有chrome的痕迹，而且我认为这是qq浏览器的，而qq和微信都会对UA信息进行自定义修改，他们改完后的内容不与标准同步比较难match
