### ISSUE TITLE
部分安卓手机无法有效区分

### ISSUE THREAD

**Issue by eidonjoe** [fex-team/ua-device#5]
魅蓝note被识别成小米m1 

原因:魅族魅蓝note UA :Mozilla/5.0 (Linux; U; Android 5.1; zh-cn;`m1 note` Build/LMY47D) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/8.8 TBS/88888888 Mobile Safari/533.1 MicroMessenger/6.3.15.49_r8aff805.760 NetType/WIFI Language/zh_CN(本机UA)

应该是匹配到了`m1` 被识别成了小米m1

**Comment by kevindu1993** [comment]
你好，感谢反馈，可以参见这里https://github.com/fex-team/ua-device/issues/3
