### ISSUE TITLE
解析结果貌似有误

### ISSUE THREAD

**Issue by airyland** [fex-team/ua-device#9]
从nginx日志随机挑了一条解析，结果是微信4.0(这里微信版本也应该是6.3.15.49)，如果内核是QQ浏览器，那么浏览器信息应该是QQ浏览器5.4，后面的device.model=M3-5这个解析结果也比较奇怪？

`Mozilla/5.0 (Linux; U; Android 5.0.1; zh-cn; M355 Build/LRX22C) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025489 Mobile Safari/533.1 MicroMessenger/6.3.15.49_r8aff805.760 NetType/WIFI Language/zh_CN`

``` javascript
{ options: { useFeatures: false, detectCamouflage: true },
  browser:
   { stock: true,
     hidden: true,
     channel: '',
     name: '微信',
     version: { original: '4.0' } },
  engine: { name: 'Webkit', version: { original: '533.1', alias: null } },
  os:
   { name: 'Android',
     version: { alias: '5.0.1', original: '5.0.1' } },
  device: { type: 'mobile', identified: false, model: 'M3-5' },
  camouflage: false,
  features: [] }

```

![image](https://cloud.githubusercontent.com/assets/559179/14197667/95bf9122-f803-11e5-9ec6-c4a0951035d5.png)

**Comment by kevindu1993** [comment]
您好，感谢反馈，问题已经修复
